kind: Deployment
apiVersion: apps/v1
metadata:
  name: veldeploy


spec:
  replicas: 1
  selector:
    matchLabels:
      name: velocity




  template:
    metadata:
      name: velpod
      labels:
        name: velocity


    spec:
      containers:
        - name: vel1
          image: httpd
          ports:
            - containerPort: 80
