kind: ReplicationController
apiVersion: v1
metadata:
  name: velocityrc


spec:
  replicas: 2
  selector:
    name: velocity





  template:
    metadata:
      name: vel-pod
      labels:
        name: velocity


    spec:
      containers:
        - name: vel-1
          image: centos
          command: ["ping", "localhost"]
